### ISSUE TITLE
Decimal is not JSON Serializable with pyzmq==22.2.1

### ISSUE THREAD

**Issue by Esquive** [hardwario/cpgw#1]
Hello Hardwario Team, 

with a new installation of the cpgw, the pyzmq version 22.2.1 was pulled. The socket.send_json(payload) from app.py throws the Decimal not JSON Serializable error. I bypassed the issue by downgrading pyzmq, so it is not blocking, just so you are aware of this issue.

**Comment by worepix** [comment]
Hello  Esquive,
thank you for your report. It has been fixed and we will tag it after proper testing.

Radim
